### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by tg1tim** [Primes11/Short-SirKit-6527#2]
hi

**Comment by Primes11** [comment]
Hello. While it's nice that you've figured out how to post an issue, please try to limit issues to actual issues, i.e. if you need programming help, or don't now how to do something.

**Comment by Primes11** [comment]
I am going to go ahead and close this issue now.

Please remember, Tim:
1.) Submit new issues for actual ISSUES
2.) comment on existing issues only when you have something constructive to add
3.) please remember that this team is a class you will be getting a grade on. I am considering submitting a report to Mr. Fink on the helpfulness and participation of each programming team member, and he might take that into account.
